### ISSUE TITLE
Seems like VapourSynth API4 broke the plugin

### ISSUE THREAD

**Issue by theChaosCoder** [ifb/vapoursynth-colorbars#7]
It now always shows this msg: `vapoursynth.Error: ColorBars: invalid format, only YUV444P10 and YUV444P12 for SDR formats`

No example from the github page is working anymore.

No problems with api3.

**Comment by myrsloik** [comment]
The problem is that format constants are directly compared without laundering them through the API first.
Happens here:
https://github.com/ifb/vapoursynth-colorbars/blob/master/colorbars.c#L765

The solution to make it work in all versions is to replace line 762 with:
`const VSFormat *vformat =  vsapi->getFormatPreset(vsapi->propGetInt(in, "format", 0, &err), core);
int pixformat = vformat ? vformat->id : 0;`
